version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-management-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: EMPLOYEE_MANAGEMENT
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
